/**
 * Worker entry (OpenNext "custom worker" pattern): the SERP trailing-slash redirect, then the
 * OpenNext-generated handler. Wrangler's `main` points here. This file imports build output from
 * `opennextjs-cloudflare build`, so it is excluded from `tsc`; the rule itself lives in
 * `src/lib/trailing-slash.ts`, which is type-checked and tested.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from './.open-next/worker.js'
import { trailingSlashRedirect } from './src/lib/trailing-slash'

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    return trailingSlashRedirect(new URL(request.url)) ?? openNext.fetch(request, env, ctx)
  }
} satisfies ExportedHandler<CloudflareEnv>
