/**
 * Worker entry (OpenNext "custom worker" pattern): the SERP trailing-slash redirect, then the
 * OpenNext-generated handler, with the indexing policy (`src/lib/indexing.ts`) on every
 * response and `/robots.txt` answered here. Wrangler's `main` points here. This file imports build output from
 * `opennextjs-cloudflare build`, so it is excluded from `tsc`; the rule itself lives in
 * `src/lib/trailing-slash.ts`, which is type-checked and tested.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from './.open-next/worker.js'
import { isProduction, robotsTxt, withIndexingPolicy } from './src/lib/indexing'
import { trailingSlashRedirect } from './src/lib/trailing-slash'

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url)
    const production = isProduction(env)
    if (url.pathname === '/robots.txt') {
      return withIndexingPolicy(robotsTxt(production), production)
    }
    const response = trailingSlashRedirect(url) ?? (await openNext.fetch(request, env, ctx))
    return withIndexingPolicy(response, production)
  }
} satisfies ExportedHandler<CloudflareEnv>
