/**
 * Worker entry (Wrangler `main`): the application Worker (`src/lib/app-worker.ts`) around the
 * OpenNext build. This file imports build output from `opennextjs-cloudflare build`, so it is
 * excluded from `tsc`.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from './.open-next/worker.js'
import { createAppWorker } from './src/lib/app-worker'

export default createAppWorker(openNext)
