/**
 * Worker entry for browser acceptance (`wrangler.e2e.jsonc`): the same application Worker as
 * `worker.ts`, around the build `scripts/e2e-server.ts` keeps apart from the developer's
 * `.open-next`. Excluded from `tsc` because the build may not exist yet.
 */
import { createAppWorker } from '../src/lib/app-worker'
// @ts-expect-error generated by `scripts/e2e-server.ts`
import openNext from '../tmp/e2e/.open-next/worker.js'

export default createAppWorker(openNext)
